### ISSUE TITLE
Workflow "Update project on PR edit" failing with 401

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar-update-companion#6]
See this check failure https://github.com/centerofci/mathesar-update-companion/actions/runs/3969063042/jobs/6803045825 in this PR https://github.com/centerofci/mathesar-update-companion/pull/2.

**Comment by kgodey** [comment]
I forgot to allow the repo access to the correct GitHub token. Should be fixed.

I also updated the checklist in https://github.com/centerofci/mathesar/issues/2209 (so we can use it as a reference for future new repos)
